# Generated by makemake
CFLAGS  = -std=c++17 -Wall -g -I/usr/include/SDL2/ # -I/usr/include/eigen3/ -fopenmp
LDFLAGS = -lSDL2

CC = g++
RM = rm -f

EXE = main
HEADERS = Constants.h Game.h GameObject.h GameSnow.h Player.h Snowflake.h SnowflakeNoContact.h SnowflakeRebound.h SnowflakeSine.h 
OBJS = Game.o GameObject.o GameSnow.o main.o Player.o Snowflake.o SnowflakeNoContact.o SnowflakeRebound.o SnowflakeSine.o 

ALL : $(EXE)

Game.o: Game.cpp Game.h 
	$(CC) $(CFLAGS) -c -o $@ $<

GameObject.o: GameObject.cpp GameObject.h Player.h 
	$(CC) $(CFLAGS) -c -o $@ $<

GameSnow.o: GameSnow.cpp Constants.h Game.h GameObject.h GameSnow.h Player.h Snowflake.h SnowflakeNoContact.h SnowflakeRebound.h SnowflakeSine.h 
	$(CC) $(CFLAGS) -c -o $@ $<

main.o: main.cpp Constants.h Game.h GameObject.h GameSnow.h Player.h Snowflake.h 
	$(CC) $(CFLAGS) -c -o $@ $<

Player.o: Player.cpp Constants.h GameObject.h Player.h 
	$(CC) $(CFLAGS) -c -o $@ $<

Snowflake.o: Snowflake.cpp Constants.h GameObject.h Player.h Snowflake.h 
	$(CC) $(CFLAGS) -c -o $@ $<

SnowflakeNoContact.o: SnowflakeNoContact.cpp Constants.h GameObject.h Player.h Snowflake.h SnowflakeNoContact.h 
	$(CC) $(CFLAGS) -c -o $@ $<

SnowflakeRebound.o: SnowflakeRebound.cpp Constants.h GameObject.h Player.h Snowflake.h SnowflakeRebound.h 
	$(CC) $(CFLAGS) -c -o $@ $<

SnowflakeSine.o: SnowflakeSine.cpp Constants.h GameObject.h Player.h Snowflake.h SnowflakeSine.h 
	$(CC) $(CFLAGS) -c -o $@ $<


$(EXE) : $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(EXE) $(LDFLAGS)

clean :
	$(RM) $(OBJS) $(EXE)
